{*************************************************************
*                                                           *
*     Copyright (c) QUINN-CURTIS, 1992, 1993                *
*                                                           *
*************************************************************
*                                                           *
*   Filename :   mdidemo.inc                                  *
*   Author   :   MS                                         *
*   Revision :   1.0                                        *
*   Date     :   December 23, 1992                          *
*                                                           *
*   Description: Definitions for mdidemo menu               *
*                                                           *
*************************************************************}

CONST
   WINDOWMENU  = 1;    { position of window menu     }

   IDM_FILENEW   =     2001;
   IDM_FILEEXIT   =    2002;
   IDM_WINDOWTILE  =   3001;
   IDM_WINDOWCASCADE=  3002;
   IDM_WINDOWCLOSEALL= 3003;
   IDM_WINDOWICONS   = 3004;
   IDM_WINDOWCHILD   = 3100;

{*************************************************************}


